# -*- coding: utf-8 -*-
"""CIE1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPsA9I1jU139iHjIeUMQIeVbJJxD4K9u
"""

import pandas as pd
data=pd.read_csv("mtcars.csv")
data

import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
plt.hist(data['mpg'],bins=10,edgecolor='black')
plt.xlabel("miles per gallon")
plt.ylabel("Frequency")
plt.title("Histogram of frequency by mpg")
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
plt.scatter(data['wt'],data['mpg'],color='blue',alpha=0.7)
plt.xlabel("Weight of cars")
plt.ylabel("Mpg")
plt.title("Scatter plot between weight and mpg")
plt.show()

import matplotlib.pyplot as plt
tc=data['am'].value_counts()
plt.figure(figsize=(10,6))
tc.plot(kind="bar",color="skyblue")
plt.xlabel("Cars 0=Automatic,1=Mannual")
plt.ylabel("Frequency")
plt.title("Bar plot frequency by cars")
plt.xticks(rotation=0)
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
plt.boxplot(data['mpg'],vert=True)
plt.xlabel("mpg")
plt.title("Box plot of mpg")
plt.show()

summary=data['mpg'].describe()
print(summary)